config/routes.rb
Rails.application.routes.draw do

  # root to: 'articles#index'
  root to: 'articles#top_page'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # User
  # Heroku用にUserの新規作成を行えないようにする
  # resources :users, except: [:destroy, :new, :create, :edit, :update] do
  resources :users, except: [:destroy] do

    member do
      post 'disable', to: 'users#disable'
      post 'enable', to: 'users#enable'
    end

    collection do
      get 'search', to: 'users#search'
    end

  end

  # Group
  resources :groups

  # Article
  resources :articles do
    member do
      # 記事をゴミ箱に入れる
      post 'disposal', to: 'articles#disposal'

      # 記事をゴミ箱から復元する
      post 'restore', to: 'articles#restore'

      # ある記事に対していいねしたユーザーを表示する
      get 'liked_user', to: 'articles#liked_user'
    end

    collection do
      # ゴミ箱に入れた記事を表示する
      get 'deleted', to: 'articles#deleted'

      # 下書き記事の一覧を表示する
      get 'drafts', to: 'articles#drafts'
      
      # 記事の検索
      get 'search', to: 'articles#search'

      # 記事に画像を埋め込む
      post 'attach', to: 'articles#attach'
    end
  end

  # Tag
  resources :tags do
    collection do
      post 'add', to: 'tags#add'
    end
  end
  
  # Like
  post '/likes/:article_id', to: 'likes#create'
  delete '/likes/:article_id', to: 'likes#destroy'

  # History
  get '/articles/:article_id/histories/:id', to: 'articles#history_view'
  post '/articles/:article_id/histories/:id', to: 'articles#revert'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
  before_validation :set_titleless_title
  before_validation :set_permalink

  paginates_per 50

  validates :user_id, presence: true
  validates :permalink, 
    presence: true,
    length: { minimum: 3, maximum: 100, message: "の長さは3文字以上200文字以下で設定してください" },
    uniqueness: { case_sensitive: false },
    format: { with: /\A^[a-z][\-a-z0-9]+\z/, message: "の最初の文字は半角英字のみで、それ以降の文字には半角英数字とハイフンを使用することができます" },
    exclusion: { in: %w(new deleted drafts search attach histories),
      message: "%{value}は予約済みの文字列のため使用できません" }
    # allow_blank: true,

  validates :status, presence: true, inclusion: { in: %w(closed opened limited) }
  validates :coedit_permit, presence: true, inclusion: { in: %w(self any selected) }

  validates :title, length: { maximum: 200 }

  belongs_to :user

  has_many :tag_assignments, dependent: :destroy
  has_many :tags, through: :tag_assignments
  accepts_nested_attributes_for :tag_assignments, allow_destroy: true

  # likes UserとArticleの多対多の関連付け
  has_many :likes, dependent: :destroy
  has_many :users, through: :likes

  # histories ArticleとHistoryの一対多の関連付け
  has_many :histories

  # ReadableArticleUserAssignment 記事の表示権限をユーザーごとに設定する
  # ArticleとUserを関連付ける
  has_many :readable_article_user_assignments, dependent: :destroy
  has_many :readable_article_users, through: :readable_article_user_assignments, source: :user
  accepts_nested_attributes_for :readable_article_user_assignments, allow_destroy: true

  # ReadableArticleGroupAssignment 記事の表示権限をグループごとに設定する
  # ArticleとGroupを関連付ける
  has_many :readable_article_group_assignments, dependent: :destroy
  has_many :readable_article_groups, through: :readable_article_group_assignments, source: :group
  accepts_nested_attributes_for :readable_article_group_assignments, allow_destroy: true

  # WritableArticleUserAssignment 記事の編集権限をユーザーごとに設定する
  # ArticleとUserを関連付ける
  has_many :writable_article_user_assignments, dependent: :destroy
  has_many :writable_article_users, through: :writable_article_user_assignments, source: :user
  accepts_nested_attributes_for :writable_article_user_assignments, allow_destroy: true

  # WritableArticleGroupAssignment 記事の編集権限をグループごとに設定する
  # ArticleとGroupを関連付ける
  has_many :writable_article_group_assignments, dependent: :destroy
  has_many :writable_article_groups, through: :writable_article_group_assignments, source: :group
  accepts_nested_attributes_for :writable_article_group_assignments, allow_destroy: true

  enum status: {
    closed: 0, #非公開,下書き
    opened: 1, #公開
    limited: 2 #公開を限定する
  }

  enum coedit_permit: {
    self: 0, # 自分のみ編集可
    any: 1, # 誰でも編集可
    selected: 2 # 編集者を選択する
  }

  # パーマリンクをidではなくpermalinkの文字列にする
  def to_param
    permalink
  end

  # private

  private def set_titleless_title
    self.title = '題名なし' if title.blank?
  end

  private def set_permalink
    if permalink.blank?

      unless Article.maximum("id").nil?
        max_plus_one = Article.maximum("id") + 1  
      else
        max_plus_one = 1
      end

      set_permalink_name = "article" + max_plus_one.to_s
      self.permalink = set_permalink_name

    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  # 該当記事の編集権限をカレントユーザーが有しているかの確認
  before_action :edit_article_permit, only: [:edit, :update]

  # 記事作成または編集時に、読み書き権限の設定が可能なユーザーとグループを変数にしてViewに渡す
  before_action :set_readables_and_writables_users, only: [:new, :create, :edit, :update]

  # 管理者が該当の記事の完全に削除する際の確認
  before_action :destroy_article_permit, only: [:destroy]

  # カレントユーザーが自身の記事を削除または復元する際の確認
  before_action :garbage_article_permit, only: [:disposal, :restore]

  # 更新履歴の確認、記事の内容を戻す際の権限確認
  before_action :edit_history_permit, only: [:history_view, :revert]

  # Ransackによる検索機能
  before_action :set_q, only: [:index, :show, :search]


  # トップページ
  def top_page
    @article = Article.first
    @histories = @article.histories.includes(:user).order(created_at: :desc).limit(10)
  end

  def index

    article_ids = current_user.get_article_ids(current_user)

    @articles = Article
      .where.not(id: 1)
      .where(id: article_ids, status: [1, 2], garbage: false)
      .includes(:user, {user: {user_image_attachment: :blob}}, :tags, :histories, :likes)
      .order(created_at: :desc)
      .page(params[:page])

  end

  # Ransackによる検索結果一覧
  def search

    article_ids = current_user.get_article_ids(current_user)

    @results = @q.result(distinct: true)
      .where.not(id: 1)
      .where(id: article_ids, status: [1, 2], garbage: false)
      .includes(:user, {user: {user_image_attachment: :blob}}, :tags, :histories, :likes)
      .order(created_at: :desc)
      .page(params[:page])

  end

  def show

    article = Article.find_by!(permalink: params[:id])
  
    if article.user_id == current_user.id

      # 記事の著者がカレントユーザーなら、公開状態も削除されたかも関係なく閲覧できる
      @article = current_user.articles.includes(:tags, :histories, :likes)
        .find_by!(permalink: params[:id])

    elsif article.limited? \
      && current_user.article_readable?(article, current_user.id)

      # 記事が読み取りユーザーの限定をしており、記事がカレントユーザーに読み取り許可されている場合
      @article = Article.includes(:tags, :histories, :likes)
        .find_by!(permalink: params[:id], garbage: false)

    else

      @article = Article.includes(:tags, :histories, :likes)
        .find_by!(permalink: params[:id], status: 1, garbage: false)

    end

    @histories = @article.histories.select(:id, :user_id, :article_id, :created_at).includes(:user).order(created_at: :desc).limit(10)

  end

  # 画像添付
  def attach
    attachment = Attachment.create! image: params[:image]
    render json: { filename: url_for(attachment.image) }
  end

  def new
    @article = Article.new
    # @tag = Tag.new
  end

  def create
    @article = current_user.articles.new(article_params)
    if @article.save

      @history = @article.histories.new(
        user_id: current_user.id,
        title: @article.title,
        content: @article.content
      )
      @history.save

      redirect_to article_url(@article), notice: "#{@article.title}を作成しました。"
    else
      render :new
    end
  end

  def edit
    # @tag = Tag.new  
  end

  def history_view
  end
  
  # 記事の内容を変更履歴から復元する場合
  def revert
    @article.title = @history.title
    @article.content = @history.content
  
    if @article.id == 1
  
      if @article.save
  
        @new_history = @article.histories.new(
          user_id: current_user.id,
          title: @article.title,
          content: @article.content
        )
        @new_history.save
  
        redirect_to root_url, notice: "#{@article.title}の内容を復元しました。"
  
      else
        render :edit
      end
  
    else
  
      if @article.save
  
      @new_history = @article.histories.new(
        user_id: current_user.id,
        title: @article.title,
        content: @article.content
      )
      @new_history.save
  
      redirect_to article_url(@article), notice: "#{@article.title}の内容を復元しました。"
  
      else
        render :edit
      end
  
    end
  
  end

  # HACK: もう少し綺麗なコードにできると思う
  def update

    if @article.id == 1

      if @article.update(top_article_params)

        @history = @article.histories.new(
          user_id: current_user.id,
          title: @article.title,
          content: @article.content
        )
        @history.save

        redirect_to root_url, notice: "#{@article.title}を更新しました。"

      else
        render :edit
      end

    elsif @article.user_id == current_user.id

      if @article.update(article_params)

        @history = @article.histories.new(
          user_id: current_user.id,
          title: @article.title,
          content: @article.content
        )
        @history.save

        redirect_to article_url(@article), notice: "#{@article.title}を更新しました。"

      else
        render :edit
      end

    else

      # 共同編集権限があったとしても、article.idがcurrent_user.idではない場合は、渡すパラメータを制限する
      if @article.update(other_user_article_params)

        @history = @article.histories.new(      
          user_id: current_user.id,
          title: @article.title,
          content: @article.content
        )
        @history.save

        redirect_to article_url(@article), notice: "#{@article.title}を更新しました。"

      else
        render :edit
      end

    end

  end

  # 特定の記事をいいねしたユーザーを表示する
  def liked_user

    article = Article.find_by(permalink: params[:id])

    if article.user_id == current_user.id

      @article = article

    elsif article.limited? \
      && current_user.article_readable?(article, current_user.id) \
      && article.garbage == false

      @article = article

    elsif article.opened? && article.garbage == false

      @article = article

    end

    liked_user_ids = @article.likes.pluck(:user_id)

    @users = User.where(id: liked_user_ids).includes({user_image_attachment: :blob})

    # NOTE: 上記のコード2行で実現できるかも SQLリクエストも減る?
    # liked_user_ids = Like.where(article_id: Article.find_by(permalink: params[:id], status: 1, garbage: false).select(:id)).pluck(:user_id)
    # @users =  User.where(id: liked_user_ids).includes({user_image_attachment: :blob})
    
  end

  # カレントユーザの保持している下書きを一覧表示する
  def drafts
    @articles = current_user.articles.where(status: 0, garbage: false)
      .includes(:user, {user: {user_image_attachment: :blob}}, :tags, :histories, :likes)
      .order(created_at: :desc)
      .page(params[:page])
  end

  # カレントユーザの、ゴミ箱に入れた記事を出力する
  def deleted
    @articles = current_user.articles.where(garbage: true)
      .includes(:user, {user: {user_image_attachment: :blob}}, :tags, :histories, :likes)
      .order(created_at: :desc)
      .page(params[:page])
  end

  # 記事をゴミ箱に入れる
  def disposal
    if @article.garbage == false
      @article.garbage = true
      @article.save
      redirect_to articles_url, notice: "#{@article.title}を削除しました。"
    else
      render :show
    end
  end

  # 記事をゴミ箱から復元する
  def restore
    if @article.garbage == true
      @article.garbage = false
      @article.save
      redirect_to articles_url, notice: "#{@article.title}を復元しました。"
    else
      render :show
    end
  end

  # 記事をDBからハードデリートする 管理者のみが実行可能
  def destroy
    @article.destroy
    redirect_to articles_url, notice: "#{@article.title}を完全に削除しました。"
  end

  # private

  private def article_params
    params.require(:article).permit(:title, :content, :permalink, :status, :garbage, :coedit_permit, { tag_ids: [] }, { readable_article_user_ids: [] }, { readable_article_group_ids: [] }, { writable_article_user_ids: [] }, { writable_article_group_ids: [] })
  end

  private def other_user_article_params
    params.require(:article).permit(:title, :content, :permalink, { tag_ids: [] })
  end

  private def top_article_params
    params.require(:article).permit(:title, :content, :permalink)
  end

  private def edit_article_permit

    article = Article.find_by(permalink: params[:id], garbage: false)

    if article.user_id == current_user.id

      @article = article

    elsif article.selected? \
      && article.opened? \
      && current_user.article_writable?(article, current_user.id)

      @article = article

    elsif article.selected? \
      && article.limited? \
      && current_user.article_writable?(article, current_user.id) \
      && current_user.article_readable?(article, current_user.id)

      @article = article

    elsif article.any? \
      && article.limited? \
      && current_user.article_readable?(article, current_user.id)

      @article = article

    elsif article.any? \
      && article.opened?

      @article = article

    end

    @histories = @article.histories.select(:id, :user_id, :article_id, :created_at).includes(:user).order(created_at: :desc).limit(10)

  end

  # 管理者のみが記事を完全に削除できるようにする
  private def destroy_article_permit
    article = Article.find_by(permalink: params[:id])
    if current_user.admin? && article.id != 1
      @article = article
    end
  end

  # カレントユーザのみが記事をゴミ箱に入れたり復元したりできる
  private def garbage_article_permit
    article = Article.find_by(permalink: params[:id])
    if article.user_id == current_user.id && article.id != 1
      @article = article
    end
  end

  # History
  private def edit_history_permit

    article = Article.find_by(id: params[:article_id], garbage: false)

    if article.user_id == current_user.id

      @article = article

    elsif article.selected? \
      && article.opened? \
      && current_user.article_writable?(article, current_user.id)

      @article = article

    elsif article.selected? \
      && article.limited? \
      && current_user.article_writable?(article, current_user.id) \
      && current_user.article_readable?(article, current_user.id)

      @article = article

    elsif article.any? \
      && article.limited? \
      && current_user.article_readable?(article, current_user.id)

      @article = article

    elsif article.any? \
      && article.opened?

      @article = article

    end

    @history = @article.histories.find_by(id: params[:id])
  
  end
  
  private def set_q
    # スペースで区切った複数ワードの検索処理
    unless params[:q].blank?
      words = params[:q].delete(:title_or_content_or_permalink_cont) if params[:q].present?

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_search_form.html.erb
<%# 検索 %>
<%= search_form_for(@q, url: search_articles_path, class: 'search-group search-radius clearfix') do |f| %>
  <%= f.search_field(:title_or_content_or_permalink_cont, class: 'form', placeholder: '記事の検索') %>

  <span class="search-btn-group">
    <%= button_tag(type: "submit", class: "search-btn") do %>
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
  <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
</svg>
    <% end %>
  </span>
  
  <%#= f.submit '検索', class: 'btn' %>
<% end %>

app/views/articles/history_view.js.erb
document.querySelector("#history-view-area").innerHTML = "<%= escape_javascript(render partial: 'articles/history_view', locals: { history: @history, article: @article }) %>";

app/views/articles/liked_user.html.erb
<% content_for :breadcrumbs do %>
  <li>
    <%= link_to(articles_path) do %>
      記事一覧
    <% end %>
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-right" viewBox="0 0 16 16">
    <path fill-rule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z"/>
  </svg>
  </li>

  <li>
  <%= link_to(article_path(@article)) do %>
    <%= @article.title %>
  <% end %>
  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-right" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z"/>
</svg></li>

  <li>いいねしたユーザー</li>
<% end %>

<div class="content-wrapper">

<div class="page-heading-wrapper row nopad align-top">

  <div class="page-heading col-lg">
    <h1><%= @article.title %>にいいねしたユーザー一覧</h1>
  </div>

</div>


<% if @users %>

  <% @users.each do |user| %>

    <div class="index-user">

      <div class="user-head row align-top">

        <%# ユーザー情報 %>
        <div class="user-info col-lg">
        <% if user.state? %>
          <%= link_to(user) do %>
            <div class="enable-user row-nocol align-middle">
              <% if user.user_image.attached? %>
                <%= image_tag user.user_image, class: 'user-image-index' %>
              <% else %>
                <%= image_tag 'default-user-icon.svg', class: 'user-image-index' %>
              <% end %>
              
              <div>
                <h1 class="user-name"><%= user.name %></h1>
                <span class="user-name-id">&#64;<%= user.name_id %></span>
              </div>
            </div>
          <% end %>
        <% else %>
          <%= link_to(user) do %>
            <div class="disable-user row-nocol align-middle">

              <% if user.user_image.attached? %>
                <%= image_tag user.user_image, class: 'user-image-index' %>
              <% else %>
                <%= image_tag 'default-user-icon.svg', class: 'user-image-index' %>
              <% end %>

              <div>
                <h1 class="user-name"><%= user.name %></h1>
                <span class="user-name-id">&#64;<%= user.name_id %></span>
              </div>
            </div>
          <% end %>
        <% end %>
        </div>


        <div class="user-operation-area col-lg-auto">
          <div class="row-nocol just-end">
            <% if user.id == current_user.id || current_user.admin? %>
              <%= link_to(edit_user_path(user), class: 'edit') do %>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pen" viewBox="0 0 16 16">
                <path d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001zm-.644.766a.5.5 0 0 0-.707 0L1.95 11.756l-.764 3.057 3.057-.764L14.44 3.854a.5.5 0 0 0 0-.708l-1.585-1.585z"/>
                </svg>編集
              <% end %>
            <% end %>

            <% if current_user.admin? %>

              <% if user.state? %>

                <%= link_to(disable_user_path(user), method: :post, data: { confirm: "ユーザー#{user.name}を無効にします。よろしいですか？"}, class: 'disable') do %>
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-x" viewBox="0 0 16 16">
                  <path d="M6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H1s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C9.516 10.68 8.289 10 6 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"/>
                  <path fill-rule="evenodd" d="M12.146 5.146a.5.5 0 0 1 .708 0L14 6.293l1.146-1.147a.5.5 0 0 1 .708.708L14.707 7l1.147 1.146a.5.5 0 0 1-.708.708L14 7.707l-1.146 1.147a.5.5 0 0 1-.708-.708L13.293 7l-1.147-1.146a.5.5 0 0 1 0-.708z"/>
                </svg>無効化
                <% end %>

              <% else %>

                <%= link_to(enable_user_path(user), method: :post, data: { confirm: "ユーザー#{user.name}を有効にします。よろしいですか？"}, class: 'enable') do %>
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-check" viewBox="0 0 16 16">
                  <path d="M6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H1s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C9.516 10.68 8.289 10 6 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"/>
                  <path fill-rule="evenodd" d="M15.854 5.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 0 1 .708-.708L12.5 7.793l2.646-2.647a.5.5 0 0 1 .708 0z"/>
                </svg>有効化
                <% end %>
                
              <% end %>

            <% end %>
          </div>
        </div>

      </div><%# user-head end %%>


      <div class="user-aside-area row align-top">

        <div class="user-introduction col-lg">
          <p><%= user.introduction %></p>
        </div>


        
        <div class="user-type-area col-lg-auto">
        <div class="row-nocol">
          <% if ! user.state? %>

            <p class="user-type disable-indication">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-dash-circle" viewBox="0 0 16 16">
                <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                <path d="M4 8a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7A.5.5 0 0 1 4 8z"/>
              </svg>無効なユーザー
            </p>

          <% elsif user.admin? %>

            <p class="user-type admin-indication">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-patch-check-fill" viewBox="0 0 16 16">
                <path d="M10.067.87a2.89 2.89 0 0 0-4.134 0l-.622.638-.89-.011a2.89 2.89 0 0 0-2.924 2.924l.01.89-.636.622a2.89 2.89 0 0 0 0 4.134l.637.622-.011.89a2.89 2.89 0 0 0 2.924 2.924l.89-.01.622.636a2.89 2.89 0 0 0 4.134 0l.622-.637.89.011a2.89 2.89 0 0 0 2.924-2.924l-.01-.89.636-.622a2.89 2.89 0 0 0 0-4.134l-.637-.622.011-.89a2.89 2.89 0 0 0-2.924-2.924l-.89.01-.622-.636zm.287 5.984-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L7 8.793l2.646-2.647a.5.5 0 0 1 .708.708z"/>
              </svg>管理者
            </p>

          <% end %>
        </div>
        </div><%# user-type-area end %>
        
      



      </div><%# user-aside-area end %>


    
    </div>



  <% end %>


<%#= paginate @likes %>

<% end %>

</div>

app/views/articles/new.html.erb
<% content_for :breadcrumbs do %>
  <li>
  <%= link_to(articles_path) do %>
  記事一覧
  <% end %>
  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-right" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z"/>
</svg></li>
  <li>記事の新規作成</li>
<% end %>

<div class="article-new content-wrapper">

  <% @heading_text = "記事の新規作成" %>

  <%= render partial: 'form', locals: { article: @article, heading_text: @heading_text } %>

</div>

app/views/articles/show.html.erb
<% content_for :breadcrumbs do %>
  <li>
  <%= link_to(articles_path) do %>
  記事一覧
  <% end %>
  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-right" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z"/>
</svg></li>
  <li><%= @article.title %></li>
<% end %>



<%= render partial: 'view_article' %>

app/views/articles/top_page.html.erb
<% content_for :breadcrumbs do %>
  <li>トップページ</li>
<% end %>

<%= render partial: 'view_article' %>