config/routes.rb
Rails.application.routes.draw do

  # root to: 'articles#index'
  root to: 'articles#top_page'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # User
  # Heroku用にUserの新規作成を行えないようにする
  # resources :users, except: [:destroy, :new, :create, :edit, :update] do
  resources :users, except: [:destroy] do

    member do
      post 'disable', to: 'users#disable'
      post 'enable', to: 'users#enable'
    end

    collection do
      get 'search', to: 'users#search'
    end

  end

  # Group
  resources :groups

  # Article
  resources :articles do
    member do
      # 記事をゴミ箱に入れる
      post 'disposal', to: 'articles#disposal'

      # 記事をゴミ箱から復元する
      post 'restore', to: 'articles#restore'

      # ある記事に対していいねしたユーザーを表示する
      get 'liked_user', to: 'articles#liked_user'
    end

    collection do
      # ゴミ箱に入れた記事を表示する
      get 'deleted', to: 'articles#deleted'

      # 下書き記事の一覧を表示する
      get 'drafts', to: 'articles#drafts'
      
      # 記事の検索
      get 'search', to: 'articles#search'

      # 記事に画像を埋め込む
      post 'attach', to: 'articles#attach'
    end
  end

  # Tag
  resources :tags do
    collection do
      post 'add', to: 'tags#add'
    end
  end
  
  # Like
  post '/likes/:article_id', to: 'likes#create'
  delete '/likes/:article_id', to: 'likes#destroy'

  # History
  get '/articles/:article_id/histories/:id', to: 'articles#history_view'
  post '/articles/:article_id/histories/:id', to: 'articles#revert'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord

  paginates_per 50

  validates :user_id, presence: true

  validates :slug,
    presence: true,
    uniqueness: { case_sensitive: false },
    format: { with: /\A^[a-z][\-a-z0-9]+\z/, message: "の最初の文字は半角英字のみで、それ以降の文字には半角英数字とハイフンを使用することができます" },
    length: { minimum: 3, maximum: 30 },
    exclusion: { in: %w(new search),
      message: "%{value}は予約済みです" }


  validates :name, presence: true, length: { minimum: 3, maximum: 30 }
  # validates :secret, presence: true

  def group_owner
    User.find_by(id: self.user_id)
  end

  # パーマリンクをidからslugの文字列に変更する
  def to_param
    slug
  end

  # belongs_to :user
  
  # group_user_assignments Userとの多対多の関連付け
  has_many :group_user_assignments, dependent: :destroy
  has_many :users, through: :group_user_assignments
  accepts_nested_attributes_for :group_user_assignments, allow_destroy: true

  # ReadableArticleGroupAssignment 記事の表示権限をグループごとに設定する
  # ArticleとGroupを関連付ける
  has_many :readable_article_group_assignments, dependent: :destroy
  has_many :readable_group_articles, through: :readable_article_group_assignments, source: :article

  # WritableArticleGroupAssignment 記事の編集権限をグループごとに設定する
  # ArticleとGroupを関連付ける
  has_many :writable_article_group_assignments, dependent: :destroy
  has_many :writable_group_articles, through: :writable_article_group_assignments, source: :article
  
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  before_action :edit_group_permit, only: [:edit, :update, :destroy]

  def index
    @groups = Group.all
      .order(slug: :desc)
      .page(params[:page])

      # .select(:slug, :name)
  end

  def show

    @group = Group.find_by(slug: params[:id])

    # @group = Group.includes(:users, {users: {user_image_attachment: :blob}}).find_by(slug: params[:id])

    @users = @group.users
      .includes({user_image_attachment: :blob})
      .order(name_id: :asc)
      .page(params[:page])

  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to groups_url, notice: "グループ#{@group.name}を作成しました。"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to groups_url, notice: "グループ#{@group.name}を更新しました。"
    else
      render :edit
    end
  end

  def destroy
    @group.destroy
    redirect_to groups_url, notice: "グループ#{@group.name}を削除しました。"
  end

  # private

  private def group_params
    params.require(:group).permit(:user_id, :slug, :name, :secret, { user_ids: [] })
  end

  private def edit_group_permit
    group = Group.find_by(slug: params[:id])
    if current_user.id == group.user_id || current_user.admin?
      @group = group
    end
  end


end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= javascript_pack_tag 'group/form', defer: true %>

<% if group.errors.present? %>
  <ul id="error-explanation">
    <% group.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with(model: group, local: true, class: 'form') do |f| %>

  <div class="row">

    <div class="col-lg-6">

      <%= f.label :slug %>
      <%= f.text_field :slug, class: 'form' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form' %>

      <label>プライベート</label>
      <section class="window form-group">
        <%= f.label :secret, class: 'toggle' do %>
          <%= f.check_box :secret %>
          <span>プライベート</span>
        <% end %>
        <p><small>プライベートをオンにすると、このグループに所属しているメンバーが非公開になります。</small></p>
      </section>

      <%= f.submit nil, class: 'btn' %>

    </div><%# col %>

    <div class="col-lg-6">

      <label>オーナー</label>

      <div class="window">

        <p id="group-owner-select-button" class="btn btn-radius border">オーナーを選択</p>
        
      </div><%# window %>


      <label>メンバー</label>

      <div class="window">

        <p id="group-member-select-button" class="btn btn-radius border">メンバーを選択</p>

      </div><%# window %>

    </div><%# col %>

  </div><%# row %>


  <div id="group-owners-select-area">

    <div class="group-owner-select-heading row align-top">
      <h1 class="col">グループのオーナーを選択する</h1>

      <div class="group-owners-window-close-button col">
        <div class="row-nocol just-end">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x" viewBox="0 0 16 16">
          <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
          </svg>
        </div>
      </div>

    </div>

    <div class="group-owner-select-area row">
      <%= collection_radio_buttons(:group, :user_id, User.where(state: true), :id, :name_id, checked: group.user_id) do |t| %>

        <div class="col-lg-4">
          <div class="group-owner-select-checkbox">
            <%= t.label(class: 'radio') do %>
              <%= t.radio_button %>
              <span class="group-owner-name"><%= t.object.name %></span>
              <span class="group-owner-slug">&#64;<%= t.text %></span>
            <% end %>
          </div>
        </div>

      <% end %>
    </div>

  </div>

  <div id="group-members-select-area">

    <div class="group-member-select-heading row align-top">
      <h1 class="col">グループのメンバーを選択する</h1>

      <div class="group-members-window-close-button col">
        <div class="row-nocol just-end">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x" viewBox="0 0 16 16">
          <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
          </svg>
        </div>
      </div>

    </div>

    <div class="group-member-select-area row nopad">
      <%= collection_check_boxes(:group, :user_ids, User.where(state: true), :id, :name_id, checked: group.user_ids) do |t| %>

        <div class="col-lg-4">
          <div class="group-member-select-checkbox">
            <%= t.label(class: 'checkbox') do %>
              <%= t.check_box %>
              <span class="group-member-name"><%= t.object.name %></span>
              <span class="group-member-slug">&#64;<%= t.text %></span>
            <% end %>
          </div>
        </div>

      <% end %>
    </div>

  </div>



<% end %>

app/views/groups/edit.html.erb
<% content_for :breadcrumbs do %>
  <li>
  <%= link_to(groups_path) do %>
  グループ一覧
  <% end %>
  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-right" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z"/>
  </svg></li>

  <li><%= @group.name %>の編集</li>

<% end %>


<div class="content-wrapper">

  <h1><%= @group.name %>の編集</h1>

  <%= render partial: 'form', locals: { group: @group } %>

</div>

app/views/groups/index.html.erb
<% content_for :breadcrumbs do %>
  <li>グループ一覧</li>
<% end %>

<div class="content-wrapper">

  <div class="page-heading-wrapper groups-index row nopad align-top">

    <div class="page-heading col">
      <h1>グループ</h1>
    </div>

    <div class="add-article col-auto">

      <div class="row-nocol just-end-lg">
        <p><%= link_to(new_group_path, class: 'btn') do %>
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-circle" viewBox="0 0 16 16">
          <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
          <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
          </svg>グループの作成
        <% end %></p>
      </div>

    </div>

  </div>


  <% if @groups.exists? %>

    <% @groups.each do |group| %>

      <div class="group-index">
        <div class="group-heading row align-top">

          <div class="group-name col-lg">
            <h1><%= link_to(group.name, group_path(group)) %></h1>
          </div>

          <%# グループの所有者か管理者でなければ編集と削除は行えない %>
          <% if current_user.id == group.user_id || current_user.admin? %>

            <div class="group-operation-area col-lg-auto">
              <div class="row-nocol just-end-lg">

                <%= link_to(edit_group_path(group), class: 'edit') do %>
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pen" viewBox="0 0 16 16">
                  <path d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001zm-.644.766a.5.5 0 0 0-.707 0L1.95 11.756l-.764 3.057 3.057-.764L14.44 3.854a.5.5 0 0 0 0-.708l-1.585-1.585z"/>
                  </svg>編集
                <% end %>

                <%= link_to(group, method: :delete, data: { confirm: "#{group.name}グループを削除します。よろしいですか？"}, class: 'delete') do %>
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                  <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                  <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                  </svg>削除
                <% end %>

              </div><%# row-nocol %>
            </div><%# group-operation-area %>
          <% end %>

        </div><%# group-heading %>

        <div class="group-aside-area row align-top">

          <p class="group-slug col-lg">
            <%= link_to(group.slug, group_path(group)) %>
          </p>

          <% if group.secret? %>
            <div class="group-secret-area col-lg-auto">
              <p class="group-secret-status secret-indication">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-lock-fill" viewBox="0 0 16 16">
                <path d="M8 1a2 2 0 0 1 2 2v4H6V3a2 2 0 0 1 2-2zm3 6V3a3 3 0 0 0-6 0v4a2 2 0 0 0-2 2v5a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2z"/>
                </svg>シークレット
              </p>
            </div>
          <% end %>

        </div><%# group-aside-area %>

      </div><%# group-index %>

    <% end %>

    <%= paginate @groups %>

  <% else %>
  
    <div class="not-yet-created">
      <p class="fixed-just-center-middle">グループはまだありません</p>
    </div>

  <% end %>

</div>

app/views/groups/new.html.erb
<% content_for :breadcrumbs do %>
  <li>
  <%= link_to(groups_path) do %>
  グループ一覧
  <% end %>
  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-right" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z"/>
  </svg></li>

  <li>グループの新規作成</li>

<% end %>


<div class="content-wrapper">

  <h1>グループの新規作成</h1>

  <%= render partial: 'form', locals: { group: @group } %>

</div>

app/views/groups/show.html.erb
<% content_for :breadcrumbs do %>
  <li>
  <%= link_to(groups_path) do %>
  グループ一覧
  <% end %>
  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-right" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z"/>
  </svg></li>

  <li><%= @group.name %></li>

<% end %>


<div class="content-wrapper">

  <div class="page-heading-wrapper row nopad align-top">

    <div class="page-heading col-lg-4">
      <h1><%= @group.name %></h1>
      <p class="group-slug"><%= @group.slug %></p>
    </div>

    <%# グループの所有者か管理者でなければ編集と削除は行えない %>
    <% if current_user.id == @group.user_id || current_user.admin? %>
      <div class="group-operation-area col-lg-auto">
        <div class="row-nocol just-end">
          <%= link_to(edit_group_path(@group), class: 'edit show btn btn-radius border') do %>
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pen" viewBox="0 0 16 16">
            <path d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001zm-.644.766a.5.5 0 0 0-.707 0L1.95 11.756l-.764 3.057 3.057-.764L14.44 3.854a.5.5 0 0 0 0-.708l-1.585-1.585z"/>
            </svg>編集
          <% end %>

          <%= link_to(@group, method: :delete, data: { confirm: "#{@group.name}グループを削除します。よろしいですか？"}, class: 'delete show btn btn-radius border') do %>
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
            <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
            </svg>削除
          <% end %>

        </div>
      </div>
    <% end %>
  </div>

  <div class="user-info-area row align-top">

    <div class="user-info owner col-lg">
      <% if @group.group_owner.state? %>
        <%= link_to(@group.group_owner) do %>
          <div class="enabale-user row-nocol align-middle">

            <% if @group.group_owner.user_image.attached? %>
              <%= image_tag @group.group_owner.user_image, class: 'user-image-index' %>
            <% else %>
              <%= image_tag 'default-user-icon.svg', class: 'user-image-index' %>
            <% end %>
            
            <div>
              <span class="user-name"><%= @group.group_owner.name %></span>
              <span class="user-name-id">&#64;<%= @group.group_owner.name_id %></span>
            </div>
          </div>
        <% end %>

      <% elsif @group.group_owner.state === false && current_user.admin? %>

        <%= link_to(@group.group_owner) do %>

          <div class="disable-user row-nocol align-middle">

            <% if @group.group_owner.user_image.attached? %>
              <%= image_tag @group.group_owner.user_image, class: 'user-image-index' %>
            <% else %>
              <%= image_tag 'default-user-icon.svg', class: 'user-image-index' %>
            <% end %>

            <div>
              <span class="user-name"><%= @group.group_owner.name %></span>
              <span class="user-name-id">&#64;<%= @group.group_owner.name_id %></span>
            </div>
          </div>

        <% end %>

      <% else %>

        <div class="disable-user row-nocol align-middle">
          
          <%= image_tag 'default-user-icon.svg', class: 'user-image-index' %>
          
          <div>
            <span class="user-name">無効なユーザーです</span>
            <span class="user-name-id"></span>
          </div>
        </div>
      <% end %>
    </div>

    <% if @group.secret? %>
      <p class="group-secret-status secret-indication col-lg-auto">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-lock-fill" viewBox="0 0 16 16">
        <path d="M8 1a2 2 0 0 1 2 2v4H6V3a2 2 0 0 1 2-2zm3 6V3a3 3 0 0 0-6 0v4a2 2 0 0 0-2 2v5a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2z"/>
        </svg>シークレット
      </p>
    <% end %>

  </div>


  <%# グループメンバーを表示する %>
  <% if @group.secret == false || current_user.id == @group.user_id || @users.exists?(id: current_user.id) || current_user.admin?  %>

    <% if @users %>
      <% @users.each do |user| %>

        <div class="index-user">

          <div class="user-head row align-top">

            <%# ユーザー情報 %>
            <div class="user-info col-lg">
            <% if user.state? %>
              <%= link_to(user) do %>
                <div class="enable-user row-nocol align-middle">
                  <% if user.user_image.attached? %>
                    <%= image_tag user.user_image, class: 'user-image-index' %>
                  <% else %>
                    <%= image_tag 'default-user-icon.svg', class: 'user-image-index' %>
                  <% end %>
                  
                  <div>
                    <h1 class="user-name"><%= user.name %></h1>
                    <span class="user-name-id">&#64;<%= user.name_id %></span>
                  </div>
                </div>
              <% end %>
            <% else %>
              <%= link_to(user) do %>
                <div class="disable-user row-nocol align-middle">

                  <% if user.user_image.attached? %>
                    <%= image_tag user.user_image, class: 'user-image-index' %>
                  <% else %>
                    <%= image_tag 'default-user-icon.svg', class: 'user-image-index' %>
                  <% end %>

                  <div>
                    <h1 class="user-name"><%= user.name %></h1>
                    <span class="user-name-id">&#64;<%= user.name_id %></span>
                  </div>
                </div>
              <% end %>
            <% end %>
            </div>

            <div class="user-operation-area col-lg-auto">
              <div class="row-nocol just-end-lg">
                <% if user.id == current_user.id || current_user.admin? %>
                  <%= link_to(edit_user_path(user), class: 'edit') do %>
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pen" viewBox="0 0 16 16">
                    <path d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001zm-.644.766a.5.5 0 0 0-.707 0L1.95 11.756l-.764 3.057 3.057-.764L14.44 3.854a.5.5 0 0 0 0-.708l-1.585-1.585z"/>
                    </svg>編集
                  <% end %>
                <% end %>

                <% if current_user.admin? %>

                  <% if user.state? %>

                    <%= link_to(disable_user_path(user), method: :post, data: { confirm: "ユーザー#{user.name}を無効にします。よろしいですか？"}, class: 'disable') do %>
                      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-x" viewBox="0 0 16 16">
                      <path d="M6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H1s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C9.516 10.68 8.289 10 6 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"/>
                      <path fill-rule="evenodd" d="M12.146 5.146a.5.5 0 0 1 .708 0L14 6.293l1.146-1.147a.5.5 0 0 1 .708.708L14.707 7l1.147 1.146a.5.5 0 0 1-.708.708L14 7.707l-1.146 1.147a.5.5 0 0 1-.708-.708L13.293 7l-1.147-1.146a.5.5 0 0 1 0-.708z"/>
                    </svg>無効化
                    <% end %>

                  <% else %>

                    <%= link_to(enable_user_path(user), method: :post, data: { confirm: "ユーザー#{user.name}を有効にします。よろしいですか？"}, class: 'enable') do %>
                      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-check" viewBox="0 0 16 16">
                      <path d="M6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H1s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C9.516 10.68 8.289 10 6 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"/>
                      <path fill-rule="evenodd" d="M15.854 5.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 0 1 .708-.708L12.5 7.793l2.646-2.647a.5.5 0 0 1 .708 0z"/>
                    </svg>有効化
                    <% end %>
                    
                  <% end %>

                <% end %>
              </div>
            </div>

          </div><%# user-head end %%>

          <div class="user-aside-area row align-top">

            <div class="user-introduction col-lg">
              <p><%= user.introduction %></p>
            </div>
     
            <div class="user-type-area col-lg-auto">
            <div class="row-nocol">
              <% if ! user.state? %>

                <p class="user-type disable-indication">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-dash-circle" viewBox="0 0 16 16">
                    <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                    <path d="M4 8a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7A.5.5 0 0 1 4 8z"/>
                  </svg>無効なユーザー
                </p>

              <% elsif user.admin? %>

                <p class="user-type admin-indication">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-patch-check-fill" viewBox="0 0 16 16">
                    <path d="M10.067.87a2.89 2.89 0 0 0-4.134 0l-.622.638-.89-.011a2.89 2.89 0 0 0-2.924 2.924l.01.89-.636.622a2.89 2.89 0 0 0 0 4.134l.637.622-.011.89a2.89 2.89 0 0 0 2.924 2.924l.89-.01.622.636a2.89 2.89 0 0 0 4.134 0l.622-.637.89.011a2.89 2.89 0 0 0 2.924-2.924l-.01-.89.636-.622a2.89 2.89 0 0 0 0-4.134l-.637-.622.011-.89a2.89 2.89 0 0 0-2.924-2.924l-.89.01-.622-.636zm.287 5.984-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L7 8.793l2.646-2.647a.5.5 0 0 1 .708.708z"/>
                  </svg>管理者
                </p>

              <% end %>
            </div>
            </div><%# user-type-area end %>
            
          </div><%# user-aside-area end %>
        
        </div><%# user-index %>

      <% end %><%# users.each %>

      <%= paginate @users %>

    <% end %><%# if group.users%>

  <% end %>

</div>