config/routes.rb
Rails.application.routes.draw do

  # root to: 'articles#index'
  root to: 'articles#top_page'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # User
  # Heroku用にUserの新規作成を行えないようにする
  # resources :users, except: [:destroy, :new, :create, :edit, :update] do
  resources :users, except: [:destroy] do

    member do
      post 'disable', to: 'users#disable'
      post 'enable', to: 'users#enable'
    end

    collection do
      get 'search', to: 'users#search'
    end

  end

  # Group
  resources :groups

  # Article
  resources :articles do
    member do
      # 記事をゴミ箱に入れる
      post 'disposal', to: 'articles#disposal'

      # 記事をゴミ箱から復元する
      post 'restore', to: 'articles#restore'

      # ある記事に対していいねしたユーザーを表示する
      get 'liked_user', to: 'articles#liked_user'
    end

    collection do
      # ゴミ箱に入れた記事を表示する
      get 'deleted', to: 'articles#deleted'

      # 下書き記事の一覧を表示する
      get 'drafts', to: 'articles#drafts'
      
      # 記事の検索
      get 'search', to: 'articles#search'

      # 記事に画像を埋め込む
      post 'attach', to: 'articles#attach'
    end
  end

  # Tag
  resources :tags do
    collection do
      post 'add', to: 'tags#add'
    end
  end
  
  # Like
  post '/likes/:article_id', to: 'likes#create'
  delete '/likes/:article_id', to: 'likes#destroy'

  # History
  get '/articles/:article_id/histories/:id', to: 'articles#history_view'
  post '/articles/:article_id/histories/:id', to: 'articles#revert'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  before_validation :set_admin, :set_state, :set_indication

  paginates_per 50

  validates :name_id, 
    presence: true, 
    uniqueness: { case_sensitive: false }, 
    format: { with: /\A^[a-z][\-a-z0-9]+\z/, message: "の最初の文字は半角英字のみで、それ以降の文字には半角英数字とハイフンを使用することができます" }, 
    length: { minimum: 1, maximum: 30 },
    exclusion: { in: %w(new search),
      message: "%{value}は予約済みです" }


  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, uniqueness: true
  validates :introduction, length: { maximum: 200 }

  # 画像
  has_one_attached :user_image

  # articles
  has_many :articles

  has_many :tags

  # likes Articleとの多対多の関連付け
  has_many :likes, dependent: :destroy
  has_many :like_articles, through: :likes, source: :article

  # group_user_assignments Groupとの多対多の関連付け
  has_many :group_user_assignments, dependent: :destroy
  has_many :groups, through: :group_user_assignments

  # ReadableArticleUserAssignment 記事の表示権限をユーザーごとに設定する
  # ArticleとUserを関連付ける
  has_many :readable_article_user_assignments, dependent: :destroy
  has_many :readable_user_articles, through: :readable_article_user_assignments, source: :article

  # WritableArticleUserAssignment 記事の編集権限をユーザーごとに設定する
  # ArticleとUserを関連付ける
  has_many :writable_article_user_assignments, dependent: :destroy
  has_many :writable_user_articles, through: :writable_article_user_assignments, source: :article

  # パーマリンクをidからname_idに変更する
  def to_param
    name_id
  end

  # 記事一覧にある、カレントユーザーがLikeしてるか否かの条件分岐部分のN+1問題の解消
  # Likeのuser_idにカレントユーザが含まれていないかチェック
  def already_liked?(like, current_user_id)
    like.pluck(:user_id).include?(current_user_id)
  end

  # カレントユーザーに書き込み権限のある記事かどうか判定する
  # 呼び出しはif current_user.article_writable?(article, current_user.id)
  def article_writable?(article, current_user_id)

    writable_group_ids = article.writable_article_group_assignments.pluck(:group_id)
    writable_group_ids ||= []

    writable_user_ids = GroupUserAssignment.where(group_id: writable_group_ids).pluck(:user_id)
    writable_user_ids += article.writable_article_user_assignments.pluck(:user_id)

    writable_user_ids << article.user_id

    # 重複を削除
    writable_user_ids = writable_user_ids.uniq

    # 配列の中にcurrent_userのidが含まれているか確認
    writable_user_ids&.include?(current_user_id)
  
  end

  def article_readable?(article, current_user_id)

    readable_group_ids = article.readable_article_group_assignments.pluck(:group_id)
    readable_group_ids ||= []

    readable_user_ids = GroupUserAssignment.where(group_id: readable_group_ids).pluck(:user_id)

    readable_user_ids += article.readable_article_user_assignments.pluck(:user_id)

    readable_user_ids << article.user_id

    # 重複を削除
    readable_user_ids = readable_user_ids.uniq

    # 配列の中にcurrent_userのidが含まれているか確認
    readable_user_ids&.include?(current_user_id)

    # 参考
    # elsif article.readable_article_user_assignments.exists?(user_id: current_user.id) \
    #   || GroupUserAssignment.where(group_id: readable_group_ids).exists?(user_id: current_user.id)

  end

  def get_article_ids(user)

    # 記事とユーザー間で読み取り制限を設定した記事
    # これで該当のidsをuser_article_ids配列で取得
    user_article_ids = user.readable_article_user_assignments.pluck(:article_id)
    user_article_ids ||= []

    # 記事とグループ間での読み取り制限を設定した記事
    # これで該当のidsをgroup_article_ids配列に取得
    group_ids = user.group_user_assignments.pluck(:group_id)
    group_ids ||= []
    group_article_ids = ReadableArticleGroupAssignment.where(group_id: group_ids).pluck(:article_id)
    group_article_ids ||= []

    # カレントユーザーの限定公開にしている記事を出力
    current_article_ids = user.articles.where(status: 2).pluck(:id)
    current_article_ids ||= []

    # 公開されている記事の取得
    general_article_ids = Article.where(status: 1).pluck(:id)
    general_article_ids ||= []

    # 該当する全ての記事のidsをarticle_idsにまとめる
    article_ids = user_article_ids + group_article_ids + current_article_ids + general_article_ids

    # 重複しているidを削除
    @article_ids = article_ids.uniq

  end

  # private

  private def set_admin
    self.admin = false if admin.nil?
  end

  private def set_state
    self.state = true if state.nil?
  end

  private def set_indication
    self.indication = false if indication.nil?
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # 管理者でなければnew, create, disable, enableは行えない
  before_action :require_admin, only: [:new, :create, :disable, :enable]

  # 自分のアカウントのedit, updateは行える。他ユーザのedit, updateは行うことができないようにする
  # カレントユーザが管理者であれば他ユーザーのedit, updateも行うことができる
  before_action :ensure_correct_user, only: [:edit, :update]

  # Ransackによる検索
  before_action :set_q, only: [:index, :show, :search]

  # Ransackによる検索
  def search
    if current_user.admin?
      @results = @q.result(distinct: true)
        .order(name_id: :asc)
        .page(params[:page])
    else
      @results = @q.result(distinct: true)
        .where(state: true)
        .order(name_id: :asc)
        .page(params[:page])
    end
  end

  def index
    if current_user.admin?
      @users = User.all
        .includes({user_image_attachment: :blob})
        .order(name_id: :asc)
        .page(params[:page])
    else
      @users = User.where(state: true)
        .includes({user_image_attachment: :blob})
        .order(name_id: :asc)
        .page(params[:page])
    end
  end

  def show

    article_ids = current_user.get_article_ids(current_user)

    if current_user.admin?
      @user = User.find_by(name_id: params[:id])
    else
      @user = User.find_by(name_id: params[:id], state: true)
    end

    # 各ユーザの記事一覧を出力
    if @user.id == current_user.id
      @articles = @user.articles
        .where.not(id: 1)
        .where(status: [0, 1, 2], garbage: false)
        .includes(:tags, :likes)
        .order(created_at: :desc)
        .page(params[:page])
    else
      @articles = @user.articles
        .where.not(id: 1)
        .where(id: article_ids, status: [1, 2], garbage: false)
        .includes(:tags, :likes)
        .order(created_at: :desc)
        .page(params[:page])
    end

    # ユーザーがいいねした記事を出力する
    like_ids = @user.likes.pluck(:article_id)
    @liked_articles = Article
      .where(id: like_ids)
      .where(id: article_ids, status: [1, 2], garbage: false)
      .includes(:user, {user: {user_image_attachment: :blob}}, :tags, :histories, :likes)
      .page(params[:page])

  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params_admin)

    if @user.save
      redirect_to user_url(@user), notice: "#{@user.name}をユーザー登録しました。"
    else
      render :new
    end
  end

  def edit
  end

  def update

    # TODO: @user.user_image.purgeで古い画像を削除しておく?

    if current_user.admin?
      if @user.update(user_params_admin)
        redirect_to user_url(@user), notice: "#{@user.name}のユーザー情報を更新しました。"
      else
        render :edit
      end

    else

      if @user.update(user_params)
        redirect_to user_url(@user), notice: "#{@user.name}のユーザー情報を更新しました。"
      else
        render :edit
      end

    end
  end

  def disable
    @user = User.find_by(name_id: params[:id])
    @user.state = false
    if @user.save
      redirect_to users_url, notice:  "#{@user.name}のユーザーアカウントを無効にしました。"
    else
      render :show 
    end
  end

  def enable
    @user = User.find_by(name_id: params[:id])
    @user.state = true
    if @user.save
      redirect_to users_url, notice:  "#{@user.name}のユーザーアカウントを有効にしました。"
    else
      render :show
    end
  end

  # private

  # user_paramsの種類を増やす?
  # adminがユーザーのcreateをする際は:user_imageや:introductionを触る必要はない
  # adminが他ユーザーのupdateをする際は:user_imageや:introductionに加えて:nameや:passwordを変える必要はない
  # adminが自身のプロフィールをupdateする際は制限はない
  # 普通のuserが自身のプロフィールをupdateする際は現在のuser_paramsでよい

  private def user_params_admin
    params.require(:user).permit(:name_id, :name, :email, :user_image, :introduction, :admin, :state, :password, :password_confirmation)
  end

  private def user_params
    params.require(:user).permit(:name_id, :name, :email, :user_image, :introduction, :password, :password_confirmation)
  end

  private def require_admin
    redirect_to root_url unless current_user.admin?
  end

  private def ensure_correct_user
    user = User.find_by(name_id: params[:id])
    if user.id == current_user.id || current_user.admin?
      @user = user
    end
  end

  private def set_q
    # スペースで区切った複数ワードの検索処理
    unless params[:q].blank?
      words = params[:q].delete(:name_or_name_id_or_email_cont) if params[:q].present?
      if words.present?
        params[:q][:groupings] = []
        words.split(/[ 　]/).each_with_index do |word, i| 
          params[:q][:groupings][i] = { name_or_name_id_or_email_cont: word }
        end
      end
    end
    # Ransackを用いた検索
    @q = User.ransack(params[:q])
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<% if user.errors.present? %>
  <ul id="error-explanation">
    <% user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>



<%= form_with(model: user, local: true, class: 'form') do |f| %>


<div class="row">


  <div class="col-lg-9">

    <%= f.label :name_id %>
    <%= f.text_field :name_id, class: 'form' %>

    <%= f.label :name %>
    <%= f.text_field :name, class: 'form' %>

    <%= f.label :email %>
    <%= f.text_field :email, class: 'form' %>

    <%= f.label :introduction %>
    <%= f.text_area :introduction, class: 'form' %>

    <% if current_user.admin? %>

      <%= f.label :admin, class: 'toggle' do %>
        <%= f.check_box :admin %>
        <span>管理者権限をつける</span>
      <% end %>
    
      <%= f.label :state, class: 'toggle' do %>
        <%= f.check_box :state %>
        <span>ユーザーの有効</span>
      <% end %>

    <% end %>

    <%= f.label :password, 'パスワード' %>
    <%= f.password_field :password, class: 'form' %>

    <%= f.label :password_confirmation, 'パスワードの確認' %>
    <%= f.password_field :password_confirmation, class: 'form' %>

    <%= f.submit '登録する', class: 'btn' %>
    
  </div>


  <div class="col-lg-3 order-first order-lg-last">
    <%# 画像 %>
    <label>プロフィール画像</label>

    <div class="window">
      <%= f.label :user_image do %>
        <%= f.file_field :user_image, class: 'form btn file-upload' %>
        <div class="btn btn-radius border user-profile-file-upload" type="button">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-image" viewBox="0 0 16 16">
          <path d="M6.002 5.5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z"/>
          <path d="M2.002 1a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V3a2 2 0 0 0-2-2h-12zm12 1a1 1 0 0 1 1 1v6.5l-3.777-1.947a.5.5 0 0 0-.577.093l-3.71 3.71-2.66-1.772a.5.5 0 0 0-.63.062L1.002 12V3a1 1 0 0 1 1-1h12z"/>
          </svg>ファイルを選択
        </div>
      <% end %>

      <div id="new-image" class="user-profile-image">
        <% if user.user_image.attached? %>
          <%= image_tag user.user_image, class: 'new-img' %>
        <% end %>
      </div>

    </div>

  </div>


</div>

<% end %>

app/views/users/_search_form.html.erb
<%# 検索 %>
<%= search_form_for(@q, url: search_users_path, class: 'search-group search-radius clearfix') do |f| %>
  <%= f.search_field(:name_or_name_id_or_email_cont, class: 'form', placeholder: 'ユーザーの検索') %>

  <span class="search-btn-group">
    <%= button_tag(type: "submit", class: "search-btn") do %>
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
  <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
</svg>
    <% end %>
  </span>
  
  <%#= f.submit '検索', class: 'btn' %>
<% end %>

app/views/users/edit.html.erb
<% content_for :breadcrumbs do %>
  <li>
  <%= link_to(users_path) do %>
  ユーザー一覧
  <% end %>
  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-right" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z"/>
  </svg></li>

  <li><%= @user.name %>のプロフィールを編集</li>

<% end %>


<div class="content-wrapper">

  <h1><%= @user.name %>のプロフィールを編集</h1>

  <%= render partial: 'form', locals: { user: @user } %>

</div>

app/views/users/new.html.erb
<% content_for :breadcrumbs do %>
  <li>
  <%= link_to(users_path) do %>
  ユーザー一覧
  <% end %>
  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-right" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z"/>
  </svg></li>

  <li>ユーザーの新規登録</li>

<% end %>

<div class="content-wrapper">

  <h1>ユーザーの新規登録</h1>

  <%= render partial: 'form', locals: { user: @user } %>

</div>

app/views/users/search.html.erb
<% content_for :breadcrumbs do %>
  <li>
  <%= link_to(users_path) do %>
  ユーザー一覧
  <% end %>
  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-right" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z"/>
</svg></li>
  <li>"<% params[:q][:groupings].each do |num| %>
      <%= num[:name_or_name_id_or_email_cont] %>
    <% end %>"の検索結果</li>
<% end %>

<div class="content-wrapper">

  <div class="page-heading-wrapper row nopad align-top">

    <div class="page-heading col-lg">
      <h1>"<% params[:q][:groupings].each do |num| %>
        <%= num[:name_or_name_id_or_email_cont] %>
      <% end %>"の検索結果</h1>
    </div>

    <div class="search-area col-lg-auto">
      <%# 検索 %>
      <%= render partial: 'search_form' %>
    </div>


    <div class="add-user col-lg-auto">

      <div class="row-nocol just-end">
        <% if current_user.admin? %>
          <p><%= link_to(new_user_path, class: 'btn') do %>
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-plus-fill" viewBox="0 0 16 16">
            <path d="M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
            <path fill-rule="evenodd" d="M13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5z"/>
            </svg>ユーザーの作成
          <% end %></p>
        <% end %>
      </div>

    </div>

  </div>




  <% @results.each do |user| %>


    <div class="index-user">

      <div class="user-head row align-top">

        <%# ユーザー情報 %>
        <div class="user-info col-lg">
        <% if user.state? %>
          <%= link_to(user) do %>
            <div class="enable-user row-nocol align-middle">
              <% if user.user_image.attached? %>
                <%= image_tag user.user_image, class: 'user-image-index' %>
              <% else %>
                <%= image_tag 'default-user-icon.svg', class: 'user-image-index' %>
              <% end %>
              
              <div>
                <h1 class="user-name"><%= user.name %></h1>
                <span class="user-name-id">&#64;<%= user.name_id %></span>
              </div>
            </div>
          <% end %>
        <% else %>
          <%= link_to(user) do %>
            <div class="disable-user row-nocol align-middle">

              <% if user.user_image.attached? %>
                <%= image_tag user.user_image, class: 'user-image-index' %>
              <% else %>
                <%= image_tag 'default-user-icon.svg', class: 'user-image-index' %>
              <% end %>

              <div>
                <h1 class="user-name"><%= user.name %></h1>
                <span class="user-name-id">&#64;<%= user.name_id %></span>
              </div>
            </div>
          <% end %>
        <% end %>
        </div>


        <div class="user-operation-area col-lg-auto">
          <div class="row-nocol just-end">
            <% if user.id == current_user.id || current_user.admin? %>
              <%= link_to(edit_user_path(user), class: 'edit') do %>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pen" viewBox="0 0 16 16">
                <path d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001zm-.644.766a.5.5 0 0 0-.707 0L1.95 11.756l-.764 3.057 3.057-.764L14.44 3.854a.5.5 0 0 0 0-.708l-1.585-1.585z"/>
                </svg>編集
              <% end %>
            <% end %>

            <% if current_user.admin? %>

              <% if user.state? %>

                <%= link_to(disable_user_path(user), method: :post, data: { confirm: "ユーザー#{user.name}を無効にします。よろしいですか？"}, class: 'disable') do %>
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-x" viewBox="0 0 16 16">
                  <path d="M6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H1s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C9.516 10.68 8.289 10 6 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"/>
                  <path fill-rule="evenodd" d="M12.146 5.146a.5.5 0 0 1 .708 0L14 6.293l1.146-1.147a.5.5 0 0 1 .708.708L14.707 7l1.147 1.146a.5.5 0 0 1-.708.708L14 7.707l-1.146 1.147a.5.5 0 0 1-.708-.708L13.293 7l-1.147-1.146a.5.5 0 0 1 0-.708z"/>
                </svg>無効化
                <% end %>

              <% else %>

                <%= link_to(enable_user_path(user), method: :post, data: { confirm: "ユーザー#{user.name}を有効にします。よろしいですか？"}, class: 'enable') do %>
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-check" viewBox="0 0 16 16">
                  <path d="M6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H1s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C9.516 10.68 8.289 10 6 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"/>
                  <path fill-rule="evenodd" d="M15.854 5.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 0 1 .708-.708L12.5 7.793l2.646-2.647a.5.5 0 0 1 .708 0z"/>
                </svg>有効化
                <% end %>
                
              <% end %>

            <% end %>
          </div>
        </div>

      </div><%# user-head end %%>


      <div class="user-aside-area row align-top">

        <div class="user-introduction col-lg">
          <p><%= user.introduction %></p>
        </div>


        
        <div class="user-type-area col-lg-auto">
        <div class="row-nocol">
          <% if ! user.state? %>

            <p class="user-type disable-indication">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-dash-circle" viewBox="0 0 16 16">
                <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                <path d="M4 8a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7A.5.5 0 0 1 4 8z"/>
              </svg>無効なユーザー
            </p>

          <% elsif user.admin? %>

            <p class="user-type admin-indication">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-patch-check-fill" viewBox="0 0 16 16">
                <path d="M10.067.87a2.89 2.89 0 0 0-4.134 0l-.622.638-.89-.011a2.89 2.89 0 0 0-2.924 2.924l.01.89-.636.622a2.89 2.89 0 0 0 0 4.134l.637.622-.011.89a2.89 2.89 0 0 0 2.924 2.924l.89-.01.622.636a2.89 2.89 0 0 0 4.134 0l.622-.637.89.011a2.89 2.89 0 0 0 2.924-2.924l-.01-.89.636-.622a2.89 2.89 0 0 0 0-4.134l-.637-.622.011-.89a2.89 2.89 0 0 0-2.924-2.924l-.89.01-.622-.636zm.287 5.984-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L7 8.793l2.646-2.647a.5.5 0 0 1 .708.708z"/>
              </svg>管理者
            </p>

          <% end %>
        </div>
        </div><%# user-type-area end %>
        
    
      </div><%# user-aside-area end %>

    </div>

  <% end %><%# result.each end %>


  <%# ページネーション %>
  <%= paginate @results %>

</div>